- App.tsx
- src/components/pages/LogIn.tsx
- src/store/actions/apiCalls.ts
- src/store/actions/members.ts
- src/store/index.ts
- src/store/persistedReducer.ts
- src/store/reducers/members.ts
- src/store/selectors/members.ts
Closes #15 . 
Some extraneous changes as well in this PR that rename instances of uid to memberId, and mid to username. Not complete, since there are some stuff from the API that probably would need to be swapped too.
> Redirect to onboarding or home on login

- App.tsx
- package.json
- src/components/pages/LogIn.tsx
- src/store/actions/authentication.ts
- src/store/actions/index.ts
- src/store/index.ts
- src/store/reducers/index.ts
- src/store/reducers/members.ts
- src/store/selectors/apiCalls.ts
- yarn.lock
Make immutable and redux thunk types muy bueno.
> Fix dep typings

- README.md
- package.json
> Simplify README

- src/components/pages/Home.tsx
- src/components/shared/MemberSearchBar.tsx
- src/components/shared/SearchBar.tsx
It currently doesn't alphabetize
> Add member search bar

- src/components/pages/Home.tsx
- src/components/shared/MemberSearchBar.tsx
When a user selects a member from the search bar, it will return the Member object to the passed in callback.
> Add onMemberSelected callback for MemberSearchBar

- src/components/pages/Home.tsx
- src/components/pages/LogIn.tsx
- src/components/pages/Onboarding/Onboarding.tsx
- src/components/pages/Onboarding/OnboardingCamera.tsx
- src/components/pages/Onboarding/OnboardingInvite.tsx
- src/components/pages/Onboarding/OnboardingSplash.tsx
- src/components/shared/MemberSearchBar.tsx
- src/components/shared/Navigation.tsx
**Changes**
- Renamed "Onboarding" to "OnboardingSplash"
- Added "OnboardingInvite" pague which allows the user to confirm full name and inviter
- Made `keyboardShouldPersistTaps` prop  configurable on MemberSearchBar
> Add OnboardingInvite to get inviter and full name

- README.md
Added as I observe problems from the others setting up
> More setup instructions in README

- package.json
- src/components/pages/Camera/VideoPreview.tsx
- src/components/pages/LogIn.tsx
- src/components/pages/Onboarding/OnboardingVideoPreview.tsx
- types/react-native-dropdownalert/index.d.ts
- yarn.lock
Using https://github.com/testshallpass/react-native-dropdownalert
Replaced manual error alerts along onboarding flow with these dropdowns, fixed a typo in error message, and removed extra Sign Up button which would crash.
> Add dropdown error notifications

- .babelrc
- package.json
- yarn.lock
> suppress console in production build

- package.json
- src/components/pages/Discover.tsx
- src/components/pages/LeaderBoard.tsx
- src/components/shared/MemberThumbnail.tsx
- src/components/shared/Navigation.tsx
- src/helpers/memberDisplay.ts
- src/store/selectors/members.ts
- yarn.lock
Fully add the standard invite leaderboard and code stubs trust and vote leaderboard
> Native leaderboard

- package.json
- src/api/index.ts
- src/components/pages/Invite/Invite.tsx
- src/components/pages/Invite/SendInvite.tsx
- src/store/actions/members.ts
- yarn.lock
Includes basic email validation. API has not yet been changed yet server-side so the API call isn't tested yet, but figured I can check in the page beforehand.
> Add send invite page for email

- android/app/src/main/AndroidManifest.xml
- ios/mobile.xcodeproj/project.pbxproj
- ios/mobile/AppDelegate.m
- ios/mobile/Images.xcassets/AppIcon.appiconset/Contents.json
- ios/mobile/Info.plist
- src/components/pages/Onboarding/Onboarding.tsx
- src/components/shared/Navigation.tsx
`raha://invite` will send signed out user to the Onboarding page
> Accept deeplinks with scheme "raha://" to Onboarding page

- src/components/pages/Camera/VideoPreview.tsx
https://github.com/rahafoundation/raha-mobile-app/pull/117#discussion_r203543443
> Fix compress call in VideoPreview to await syntax

- src/components/pages/Camera/VideoPreview.tsx
I wrote a bug :(
Wasn't actually uploading the transcoded video.
Also removed some doubled code from a bad merge and removed minimum bitrate
> Actually upload the transcoded video

- src/components/shared/Navigation.tsx
Put the Give button on each header except Give page itself. Want to make it easier for people to transact
> Add Give button everywhere

- android/app/src/main/AndroidManifest.xml
- android/app/src/release/AndroidManifest.xml
Remove unnecessary permissions that were being pulled in by dependencies
#147
> Remove unnecessary Android permissions

- src/components/pages/Invite/Invite.tsx
- src/components/pages/Onboarding/Onboarding.tsx
- Enables send invite
- Moves deep link param initialization to after LogIn since otherwise the user is not authorized to read the download URL
- Set invitingMember only if video download URL exists
> Enable send invite

- src/components/pages/LogIn.tsx
> Fix offscreen dropdown

- src/components/pages/Camera/VideoPreview.tsx
Broken after switching over to RNFirebase. Removing it for now and just showing Uploading right away when the user clicks and resetting on error.
#157
> Remove upload snapshot 

- src/components/pages/Account.tsx
- src/store/reducers/members.ts
- src/store/selectors/me.ts
- src/store/selectors/members.ts
Add lastOpCreatedAt to calculate inactivity timer and rename lastMinted to lastBasicIncomeAt
> Add lastOpCreatedAt to calculate inactivity timer

- src/components/pages/LogIn.tsx
I would have to modify RNFirebase to add an additional hook into `onVerificationCompleted` so I just decided to put up a message instead. 
#168
> Add message that some Android devices will log in automatically

- src/components/pages/LogIn.tsx
i can't run on android, and even if i did I can't trigger firebase to auto continue log in because my phone number is on my iphone not my sim card. @rahulgi can you let me know if you still see the error related to confirmation code interval?
> only set confirmation code timer on mount

- src/components/pages/Mint.tsx
- src/store/reducers/members.ts
- src/store/selectors/activities/index.ts
[] TODO: Update GENESIS_VERIFY_OPERATION ids once PROD has been migrated.
> Migrate reducer and activity to CreateMember and Verify GENESIS operations

- android/app/build.gradle
> Make AppCenter configs optional

- src/components/pages/Mint.tsx
- src/components/pages/Profile.tsx
- src/components/shared/MintButton.tsx
> Give genesis members a verified experience

- README.md
- android/app/src/main/AndroidManifest.xml
- src/components/pages/Discover.tsx
> Only process as deeplink if using d prefix

- src/components/pages/Invite/Invite.tsx
- src/components/pages/Onboarding/Onboarding.tsx
- src/components/pages/Profile.tsx
- src/components/pages/Verify/ConfirmExistingVerificationVideo.tsx
- src/components/pages/Verify/index.tsx
- src/components/shared/Activity/index.tsx
- src/components/shared/VideoUploader.tsx
- src/components/shared/VideoWithPlaceholder.tsx
- src/store/selectors/authentication.ts
Generates thumbnails for all video uploads.
The same refactor probably ought to occur for other flows that don't use react-navigation, like onboarding and invite.
> thumbnail generation, refactor verify flow

- src/components/pages/Give/GiveForm.tsx
- src/components/pages/Give/index.tsx
- src/components/pages/LogIn.tsx
- src/components/shared/Navigation.tsx
Closes #260.
https://send.firefox.com/share/e58a631e84
https://send.firefox.com/download/8c1ba43d60/#on8kSFl_Q9gdHMfFiep-Mg
> move log in button to proper place, wrap login form in keyboard avoiding view

- src/components/pages/Onboarding/InputEmail.tsx
- src/components/pages/Onboarding/InputInviteToken.tsx
- src/components/pages/Onboarding/Onboarding.tsx
- src/components/pages/Onboarding/OnboardingCamera.tsx
Closes #261.
Video showing switching between a joint invite token to async invite token then back:  https://goo.gl/MXvtsn
Error:
> Allow user to enter an invite token manually.

- src/components/pages/Onboarding/InputInviteToken.tsx
- src/components/shared/MintButton.tsx
- src/store/selectors/me.ts
> Add current mint rate to mint page.

- src/components/pages/Give/GiveForm.tsx
- src/components/pages/LogIn.tsx
Implementing the solution from: https://github.com/facebook/react-native/issues/4099#issuecomment-307541206
@tinaroh noted that this doesn't scroll to show the button as well. Is that something we're just going to have to give up on?
> Style scrollview inner container with flexgrow 1

- src/components/pages/Onboarding/OnboardingCreateAccount.tsx
in response to Bret's bug report email
> put create account text in scroll view

- src/components/App.tsx
> Refresh ops every app foreground

- .gitignore
- README_DEPLOYMENT.md
- android/app/build.gradle
- android/app/version.gradle
- package.json
- scripts/incrementVersion.js
- yarn.lock
Script to bump version, and more thorough/less verbose deployment instructions.
Closes #338 
Closes #339
> Version bump script, deployment instructions

- README.md
> Update README deeplinking info, legacy build tip

- src/components/pages/Onboarding/OnboardingSplash.tsx
- src/components/shared/Swiper.tsx
- src/components/shared/elements/Button.tsx
- src/helpers/colors.ts
Proposal for Join Now button that shows up on every splash page, fixed to the bottom so that user can advance to camera as soon as they want (since it seems like most people don't read the text...). Inner text will scroll if the contents are longer than the device.
Demo: https://drive.google.com/file/d/1J14hv9Q63xgJkVHldOD0vfmGFQt3Kxuc/view?usp=sharing
Also:
- Adjusts the pagination bar to not be absolutely positioned and floating over the content (I put a light gray background behind it)
- Added 10 Raha/week and 3% explicitly
Fixes #246,  #14
> Make "Join Now" button show up on each splash page

- appcenter-pre-build.sh
> Fix CodePush for iOS

- src/components/pages/Profile.styles.ts
- src/components/pages/Profile.tsx
- src/components/shared/MemberName.tsx
> Add unverified label to MemberName component.

- android/data/config/firebase/google-services.prod.json
- android/data/config/firebase/google-services.test.json
Sorry, in my overzealous attempt to clear disk space I nuked my Android debug.keystore so my fingerprint changed. Re-adding them here (don't remember which one my old one was...)
> Add my SHA1s again for Firebase

- src/components/shared/Swiper.tsx
- src/helpers/colors.ts
Sorry it probably looked better for me since my soft nav bar is gray.
Previous (off Rahul's phone):
Now:
> Make onboarding pagination background black and add margins

- src/store/selectors/activities/index.ts
Doesn't change functionality; just splits function that parses operations into activities, into smaller contained functions with unified error handling.
> split op activity fns

- src/store/selectors/activities/index.ts
- src/store/selectors/activities/types.ts
This will make it possible to keep track of what operations are already applied to what activities. Not necessary but potentially useful.
> add operations to activities

- src/components/shared/Navigation.tsx
- src/helpers/colors.ts
ty @osdiab for the design feedback for the header!
- Add Invite / Give for header, remove the title for top-level pages
- Change the pinkish lavender to the purple that we use on the website
- Use purple instead of mint for the bottom nav focus tint
> Add Invite to header and navigation restyling

- src/store/selectors/activities/index.ts
- src/store/selectors/activities/types.ts
Allow for activities without bodies. Also adds some comments to the `Activity` shape
> bodyless activities

- src/components/App.tsx
- src/components/shared/Activity/index.tsx
- src/components/shared/VideoUploader.tsx
- src/store/index.ts
- src/store/reducers/dropdown.ts
- src/store/selectors/activities/index.ts
- src/store/selectors/activities/types.ts
There were a number of existing type errors in the code, a couple which caused bugs; this fixes those.
#378 also had some issues with how the types were defined—this rectifies that to prevent erroring out on displaying activities.
Could have been avoided by #111
> existing type errors and bug

- src/components/pages/AccountSettings/SignOut.tsx
- src/components/pages/Invite/InviteCamera.tsx
- src/components/pages/Invite/InviteSplash.tsx
- src/components/pages/Invite/styles.ts
- src/components/pages/Wallet.tsx
- src/components/shared/MintButton.tsx
- Removed total minted (maybe we can bring it back in some stats page?)
- No referral bonus button if there's nothing pending
- Moved the invite image to invite flow and adjusted some font sizes
> Make Mint page simpler

- src/components/pages/LeaderBoard.tsx
- src/components/shared/MemberThumbnail.tsx
Didn't spend much time styling / making the code nice. Just wanted it to not be blank
> Make leaderboard show up

- src/components/pages/Give/GiveForm.tsx
- src/components/shared/MemberName.tsx
- src/components/shared/Navigation.tsx
- src/components/shared/elements/Text.tsx
- src/components/shared/elements/TextInput.tsx
- src/helpers/colors.ts
> Make header buttons more easily selectable, make Give form have bigger font

- src/components/shared/MemberSearchBar.tsx
- src/helpers/colors.ts
> Fix member search bar color scheme and roundedness 

- src/components/pages/AccountSettings/EditMember.tsx
It was getting cut off on my phone
> Shorten "Update Profile Details" to "Update"

- src/components/shared/Camera.tsx
```
Fatal Exception: NSGenericException
*** -[AVCaptureSession startRunning] startRunning may not be called between calls to beginConfiguration and commitConfiguration
```
This issue is caused when we try to access RNCamera on iOS when the user has denied permissions. The issues were fixed around async access in https://github.com/react-native-community/react-native-camera/issues/154, but I was using [Function as Child Components ](https://github.com/react-native-community/react-native-camera/blob/master/docs/RNCamera.md#facc-function-as-child-components) which still seems to have an issue. It seems to be calling setType or something even if the user doesn't authorize.
As suggested in https://github.com/react-native-community/react-native-camera/issues/1768, I just split out to …
> Don't use FaCC for RNCamera to avoid crash

- src/components/shared/Activity/index.tsx
- src/components/shared/elements/MixedText.tsx
Button text was not horizontally centered due to the space for the first Text component.
> Don't add space to the first Text for MixedText

- src/components/shared/Navigation.tsx
> Clear out headerLeft when going to Profile

- src/components/pages/ReferralBonus/ReferralThumbnail.tsx
- src/components/pages/Wallet.tsx
- src/components/shared/MintButton.tsx
- src/components/shared/Navigation.tsx
- src/components/shared/elements/Button.tsx
- src/store/selectors/me.ts
- yarn.lock
Omar: Updated to make it look better.
> Larger mint buttons, fix Mint Invite Bonuses header

- src/components/pages/Wallet.tsx
> restyle wallet page to align button widths

- src/components/pages/Wallet.tsx
Feel free to merge this yourself if it looks good @markulrich
> undo debugging code (oops)

- package.json
- src/components/pages/Onboarding/InputEmail.tsx
- src/components/pages/Onboarding/Onboarding.tsx
- src/components/pages/Onboarding/OnboardingCreateAccount.tsx
- src/store/actions/members.ts
- yarn.lock
> Add subscribe to monthly newsletter in onboarding flow

- src/components/pages/Profile.tsx
- src/components/pages/StoryList.tsx
- src/components/shared/Navigation.tsx
- src/components/shared/StoryFeed/index.tsx
- src/components/shared/StoryFeed/styles.ts
- src/store/selectors/activities/index.ts
Flag button is now purple.
Verified members list didn't show verifications that had been bundled into `NEW_MEMBER` activities, added a function to unbundle those.
> Restyle Flag button, make Verified members list show up right

- package.json
- src/components/pages/Wallet.tsx
- src/components/shared/elements/Hint.tsx
- src/helpers/colors.ts
- yarn.lock
It shows a gray icon with "i" (default) or "?" and when you click it, it pops up a modal. Will use this to provide more info to the user throughout the app.
> Add hint icon component

- src/components/pages/LogIn.tsx
- src/components/shared/elements/TextLink.tsx
> Add tiny help link on Login page and put default link color in TextLinks

- src/store/actions/authentication.ts
Fixes #451 
Was broken on both Android and iOS
> Capture mobile validation on LogIn and show dropdown

- src/components/pages/Invite/SpecifyJointVideo.tsx
- src/components/pages/LogIn.tsx
- src/components/pages/Onboarding/InputInviteToken.tsx
- src/components/pages/Onboarding/Onboarding.tsx
- src/components/pages/Onboarding/OnboardingCreateAccount.tsx
Also forces all new members to create an identity video, regardless of whether they were invited via joint video.
Also fixes a bug in redirecting during onboarding.
> Full page invite token page during onboarding.

- src/store/actions/authentication.ts
- src/store/actions/dropdown.ts
@tinaroh or @osdiab, would appreciate verification that this resolves issue #492.
> Fix non-string action types on dropdowns.

- src/components/shared/MintButton.tsx
- src/data/prod.config.ts
- src/data/test.config.ts
- src/store/selectors/me.ts
This information will change once the mint cap transition date has been
reached to reflect the new cap.
> Add information about mint cap transition to MintButton.

- android/app/version.gradle
- ios/Raha/Info.plist
- package.json
- src/data/prod.config.ts
- src/data/test.config.ts
This reverts commit 8a2345b1d1418f4e57fb234373341c7518e772d8.
> Revert "v0.2.2 (#530)"
