rahafoundation/raha-mobile-app

App.tsx, package.json, src/components/pages/Home.tsx, src/components/pages/Onboarding.tsx, src/components/pages/OnboardingCamera.tsx, src/components/shared/Camera.tsx, yarn.lock
- Removed `react-native-camera` in favor of Expo Camera which doesn't require us to eject the apps yet
- Gets CAMERA and AUDIO permissions from user
- Fixed overstretched Home page on Android due to `minHeight: 100%` (it might just be my Galaxy S8 though). `flex: 1` seems to be enough to stretch the content.
Up next: Finish recording should advance user to a preview screen where they can upload.
*Other Issues:*
- Denying permission seems to crash Expo though, looking into that separately since stacktrace points outside our app
- I was trying to use [Camera.Constants.Type.back](https://github.com/expo/expo-sdk/blob/master/src/Camera.js#L90) as suggested [here](https://docs.expo.io/versions/latest/sdk/camera#type) but the type definition doesn't include it so I hardcoded the constants …
=> Add OnboardingCamera page which shows camera preview and prompt text

App.tsx, src/components/pages/Home.tsx, src/components/pages/OnboardingCamera.tsx, src/components/pages/VideoPreview.tsx, src/components/shared/Camera.tsx
The VideoPreview page allows the user to preview and return to OnboardingCamera if they want to retake the video.
Also adjusted the recording quality to the lowest (4:3) and disabled the flip button in OnboardingCamera.
=> Add VideoPreview screen after recording a video

App.tsx, src/api/index.ts, src/components/AuthManager.tsx, src/components/pages/Give/GiveForm.tsx, src/components/pages/Give/Success.tsx, src/components/pages/Home.tsx, src/components/pages/LogIn.tsx, src/components/pages/Onboarding/OnboardingInvite.tsx, src/components/pages/Profile.tsx, src/components/shared/ActivityFeed.tsx, src/components/shared/Navigation.tsx, src/store/actions/authentication.ts, src/store/persistedReducer.ts, src/store/reducers/authentication.ts, src/store/selectors/authentication.ts
Add a watcher to Firebase auth to handle actual logged-in status. Get
the logged-in Firebase user directly from Firebase auth library instead
of storing it in Redux. Redux authentication state is no-longer
sensitive - it just contains logged-in booleans.
bdaa1bb
=> Add AuthManager component and firebaseUser selectors.

src/components/pages/LogIn.tsx
During Onboarding, if you back out or reload the app, you're left logged in. When you are dropped into the LogIn page and try to Sign In, it doesn't do anything.
This is a temporary way to clear the authenticated state so I can more easily debug onboarding. The actual fix should clear the state on unmounting Onboarding. Issue tracking is here: https://github.com/rahafoundation/raha-mobile-app/issues/77
=> Add Clear button in LogIn page

src/components/pages/Camera/VideoPreview.tsx, src/components/pages/Onboarding/OnboardingCamera.tsx, src/components/pages/Onboarding/OnboardingVideoPreview.tsx, src/components/shared/Camera.tsx, src/components/shared/Navigation.tsx
- VideoPreview will be reused in the inviter flow. I split out the Video/retake/upload parts into a VideoPreview class. 
- InvitePreviewVideo renamed to OnboardingPreviewVideo for clarity since we will have an invite flow 
- Fixed crashes in Camera
=> Split out reusable part of InvitePreviewVideo -> VideoPreview and fix crashes

src/components/pages/Invite/Invite.tsx, src/components/pages/Invite/InviteCamera.tsx, src/components/pages/Mint.tsx, src/components/pages/Onboarding/Onboarding.tsx, src/components/shared/Camera.tsx, src/components/shared/Navigation.tsx, src/helpers/token.ts, src/store/selectors/authentication.ts
Uploads invite video to "invite-video" bucket in Firestore which prevents `list` queries but allows `get` from authenticated users. I did it through Firestore since it had precedence -- could look into uploading directly to Google Cloud Storage later.
Uses a randomly generated alphanumeric string as the token which will be forwarded in the SEND_INVITE flow through the URL send in the email which will serve as the deeplink for the recipient.  
TODO before merge:
=> Add Invite flow component and upload video

src/components/pages/Invite/Invite.tsx, src/components/pages/Invite/SendInvite.tsx
In case we decide to ship Android before I finish deeplinking, just tell users to use the web app.
Also fixed a missed renaming
=> Add temporary message for missing send invite functionality and fix error

src/components/pages/Onboarding/Onboarding.tsx, src/components/pages/Onboarding/VerifyName.tsx, src/store/selectors/members.ts
If deeplinked, pre-populate the `invitingMember` and `videoDownloadUrl` fields for Onboarding and skip unnecessary steps.
- Save steps in a stack since we skip steps for onboarding via deeplinking
I'll wait for SMS login to merge before fixing logging the user in before going through Onboarding.
=> Pipe through deeplink parameters for Onboarding

android/app/build.gradle
Android will not build if we hit > 64k methods. See: https://developer.android.com/studio/build/multidex
I hit this limit on my branch importing a library. Separating this out just in case you guys hit it.
For prod, we should enable Proguard to strip out unused methods/resources. Added an issue for it.
=> Enable multidex for Android

src/components/pages/Invite/Invite.tsx, src/components/pages/Invite/SendInvite.tsx
We should probably stop the users before they go through the Camera flow. I previously put this on the last page
=> Fix temporary Invite splash page

src/components/pages/Onboarding/Onboarding.tsx
If the user reaches Onboarding without being logged in, that means they navigated directly via deeplinking. Ask them to log in before continuing.
#76
=> Add LogIn for Onboarding via deeplink

package.json, src/components/pages/Invite/Invite.tsx, src/components/pages/Invite/SendInvite.tsx, src/components/pages/Onboarding/Onboarding.tsx, src/components/pages/Onboarding/OnboardingRequestInvite.tsx, src/store/actions/members.ts, yarn.lock
Changes:
- `request_invite` endpoint now accepts `videoToken` optionally and removes `videoDownloadUrl` (was previously a no-op). Match client to the updated raha-api.
- Used shared Button 
- Fix inverted email/videoToken params for sendInvite
- Don't allow partial deeplink params (e.g. inviter present but not videoToken)
This completes #76 but the feature shall remain disabled until #119 is complete too
=> Update client to match new mobile request invite API

README.md, android/app/build.gradle, android/data/config/firebase/google-services.prod.json, package.json
There are three apps declared:
`app.raha.mobileProd` - dev prod - "Raha Prod"
`app.raha.mobileTest` - dev test - "Raha Test"
`app.raha.mobile` - release - "Raha"
This way we can have all three versions installed on the device. And we can probably remove the dev certificates from the release build one.
=> Add a dev prod build for Android - app.raha.mobileProd

ios/RNVideoProcessing/mobile-Bridging-Header.h, ios/mobile-Bridging-Header.h, ios/mobile.xcodeproj/project.pbxproj, package.json, yarn.lock
Not sure what fixed it -- moving the mobile-Bridging-header didn't work so I removed react-native-video-processing and then re-added it (from the official GitHub account since my fix was merged) then went through all the steps again.
Seems to work now, please try with `yarn start:ios`. Seems to complain about Roboto missing but the app seems to work.
=> Fix iOS build

ios/mobile.xcodeproj/project.pbxproj, ios/mobile/Info.plist
not sure why roboto was ever imported to the app, but it doesn't exist in the fonts directory so ios build fails without this.
=> remove roboto font to fix ios build

src/components/pages/Discover.tsx, src/components/shared/Navigation.tsx
Until we have an actual in-app experience, open Discourse in external browser to avoid issues around SSO and back button.
https://github.com/rahafoundation/raha-mobile-app/issues/132
https://github.com/rahafoundation/raha-mobile-app/issues/134
=> Open Discourse in browser instead of in app webview

src/components/shared/elements/Button.tsx
`style` doesn't accept text properties.
=> fix button text style to actually work

package.json, yarn.lock
Fixes suggestions for imports in VSCode being totally wrong, otherwise the new stuff we aren't really using yet (but i'd love to!).
Also removes `react-native-scripts-ts`, which is a hold out from our `expo` days
=> typescript 3

src/components/shared/elements/Button.tsx, src/components/shared/elements/Currency.tsx, src/components/shared/elements/MixedText.tsx
Looks like there's some kind of `react-native` bug when defining the font both on the parent `Text` element and the inner `Text` element of a button. That's weird.
=> Fix Raha symbol not rendering in buttons on Android

src/components/pages/Verify/ConfirmExistingVerificationVideo.tsx
Not sure if there's a better way to do this, @osdiab. Kind of seems excessive to me to create a separate flex row just to center the video. Prior to this change the video was left-adjusted on the screen.
=> Fix video styling for verification videos.

src/components/pages/Invite/SendInvite.tsx, src/components/pages/Onboarding/InputEmail.tsx, src/components/pages/Onboarding/InputInviteToken.tsx, src/components/pages/Onboarding/VerifyName.tsx, src/components/pages/Onboarding/styles.ts
#279
Instead of making the TextInput bigger, automatically focus on the text input when the user gets to the page. Also, I brought up the cards to the start because when the keyboard comes up, it covers the input. I think it looks fine up at the top
=> Auto-focus on text inputs and bring them to the top

package.json, src/components/pages/Give/GiveForm.tsx, src/components/pages/Give/index.tsx, src/components/pages/LogIn.tsx, src/components/shared/Navigation.tsx, src/components/shared/elements/KeyboardAwareScrollContainer.tsx, src/components/shared/elements/KeyboardAwareScrollView.tsx, yarn.lock
This is a more flexbile solution to keyboard avoidance imo.
~~It's a little awk in that you get scroll animations on the pages that use it~~ (bounce=false prevents this!), but it's pretty foolproof to issues of screen size, and easy to implement.
the one awkward UI thing is that when you scroll on the login page the image goes under the header, but that's pretty minor IMO and better for it to be usable than optimally pretty.
Videos:
* https://send.firefox.com/download/b6a51a1c36/#7CfcjID6xXI-MwND1ufCng
* https://send.firefox.com/download/377b8d985b/#Sp-0-lrLGNsplr8UruPtmg
=> Use keyboard avoiding scroll view instead of keyboardavoidingview

src/components/shared/Navigation.tsx
Makes it so that
- Back still works when you navigate to someone else's profile
- Hitting profile icon in bottom tab navigation correctly pops the stack
=> Give profile tab and profile page different route names

ios/Raha.xcodeproj/project.pbxproj
Doing a clean checkout took me back to the:
```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
issue, and I went into Raha configuration and set the Pod root to Pods-Raha.debug/release
=> Fix Pod root for iOS build

android/app/build.gradle, android/build.gradle, package.json, src/components/MessagingManager.tsx, src/store/reducers/dropdown.ts, yarn.lock
RN Firebase 5.0.0-rc2 was released and claimed to have fixed the bug that was blocking this. However, it still does not work - left a comment to this regard here: https://github.com/invertase/react-native-firebase/issues/1445#issuecomment-422665302.
Opening this PR and will continue updating as conversations progresses.
=> Re-enable foreground notifications

package.json, scripts/incrementVersion.js
The increment version name doesn't work with codepush because it default tries to just pull the line from build.gradle versionName and it can't resolve getProperty.
=> Fix Codepush 

ios/Raha.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
As of 2018/09/21, when iOS 12 and XCode 12 was released, the XCode build system got updated. The new build system errors when trying to build React Native. Hopefully Facebook resolves this soon, but in the meantime use the Legacy Builder as [explained in this comment](
https://github.com/facebook/react-native/issues/20774#issuecomment-422607019).
Above text is already in README
=> iOS, XCode: use legacy build system by default

src/components/pages/Feed.tsx, src/components/pages/Profile.tsx, src/components/shared/Activity/index.tsx, src/store/selectors/activities/index.ts, src/store/selectors/activities/types.ts
Currently it's set to combine all the mint activities in 3 hour windows starting from the timestamp of the first mint activity in that set.
Required changes to allow for multiple actors in a single activity, and caching so that we don't have to search the entire space of activities every time a new operation comes in—complexity ramping up.
Also filters out `request_verifications` operations in global feed to compensate for #387 not happening
None, but this will be reworked soon after according to [this comment below](https://github.com/rahafoundation/raha-mobile-app/pull/386#issuecomment-425796360).
* @tinaroh  feels it is strange to total up multiple people's basic incomes; I think it makes sense from the perspective of giving scale to how much is being minted/what you're missing out on …
=> combine basic income mint activities

src/components/pages/Give/GiveForm.tsx
By rounding with Big after each character, we remove all decimal points that the user attempts to enter;
Instead, I now validate and round after onEndEditing is called when the user selects away from the amount FormInput.
Demo: https://drive.google.com/file/d/1lQFRbco-sloEyUsf-YxaWUMtvOq_OPNb/view?usp=sharing
=> Allow users to give amounts with decimal points

tsconfig.json
you must import, unless it's `jest` or `node`.
=> Prevent global types like `big` from lying about their presence

android/build.gradle, src/components/shared/Camera.tsx
We force-resolve to 15.0.1 for Google Play Services dependencies since not all of our dependencies are upgraded yet.
Also due to https://github.com/facebook/react-native/commit/b81c8b5 the camera was overflowing on Android so add `overflow: "hidden"`. Thanks @osdiab for the help!
=> Fix Android build and overflowing camera due to RN57 upgrade.

src/components/pages/Feed.tsx, src/components/pages/Profile.tsx, src/components/shared/Activity/ActivityFeed.tsx, src/components/shared/Navigation.tsx
If the tab is pressed while there's only one page on the stack, and the child navigator declared a `pageReset` function, it will call it.
For Feed and Profile, this will scroll the ActivityFeed to the top.
Fixes #122
=> Scroll feed back to top if user taps on same navigation tab 

ios/Raha.xcodeproj/project.pbxproj
Having it "Raha Dev" keeps changing the .app name to Raha Dev.app every time you open XCode.
Bundle display name controls the displayed name of the app on iOS devices, so revert
=> Rename Product Name back to Raha

src/components/shared/Cards/FlaggedNotice.tsx, src/components/shared/MemberName.tsx, src/components/shared/MemberThumbnail.tsx, src/components/shared/elements/TextLink.tsx
- No more state where you get stuck on your own profile
- Follows instagram style of a) navigation.push over navigation.navigate, b) can tap twice on tab to get to the "root" of that tab, c) your profile page reached from other areas of app looks different from your "Profile tab"
=> Fix profile tab navigation, use push navigation

src/components/pages/ReferralBonus/ReferralThumbnail.tsx, src/components/pages/Wallet.tsx, src/store/selectors/me.ts
Thanks Omar for your help!
We were sending in a number instead of a Big, which doesn't have round function on it.
To paraphrase Omar, TypeScript didn't catch this because Redux AsyncCreator declares `any` for the params' types. So we'll have to extend it and add types if we want it to protect us.
=> Use Big to fix minting referral bonus

README_DEPLOYMENT.md, android/app/build.gradle, package.json, scripts/checkiOSCodePushKey.sh
- Add instructions for CodePush keys for when you bundle the release versions because that's where they matter
- Add check for iOS keys in `bumpVersion`
- Add check for Android keys in gradle task
=> Make sure we have CodePush keys for app store deploys

src/components/shared/Story/index.tsx, src/store/selectors/activities/index.ts, src/store/selectors/activities/types.ts, src/store/selectors/stories/index.ts, src/store/selectors/stories/types.ts
[1/3] for tipping #460 
- Tip operations are bundled as `childrenOps` on an Activity. I keep all operations in a map and do two passes so that if we decide to change the order of operations processed, it won't break
- Tips are combined into a TIP actor CallToAction
- Condense GIVE Stories to just say "donated to Raha Basic Income" inline instead of having 3 circles
=> Bundle tip operations at activity-level

src/components/shared/navigation/Navigation.tsx
Today hitting Invite from Homefeed or Discover suddenly moves you to the wallet tab and messes up navigation. This fixes it (and makes it so that if you ever can Invite from Profile tab, that will also work).
=> Allow Invite page to be navigated to from any tab

package.json, src/components/pages/Invite/InviteSplash.tsx, src/components/pages/ReferralBonus/ReferralThumbnail.tsx, src/components/pages/ReferralBonus/index.tsx, src/components/pages/Wallet.tsx, src/components/shared/MintButton.tsx, src/store/actions/wallet.ts, src/store/selectors/activities/index.ts, src/store/selectors/activities/types.ts, src/store/selectors/me.ts, src/store/selectors/stories/index.ts, src/store/selectors/stories/types.ts, yarn.lock
Client-side of invite bonus split to 30/30.
Depends on https://github.com/rahafoundation/raha-api/pull/161 being deployed
Currently I just display the invited bonus as an independent Story. Follow up task to bundle into new user here https://github.com/rahafoundation/raha-mobile-app/issues/528
=> Split invite bonus to 30/30
